apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '>=4.0.0 <5.0.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1h
  install:
    timeout: 15m
  upgrade:
    timeout: 15m
  values:
    controller:
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "10.10.1.30"
