apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs-csi-driver
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: '>=4.9.0'
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: nfs-csi-driver
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
