apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-nfs-storage
  namespace: ubuntu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
