apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-smb-storage
  namespace: ubuntu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: ubuntu-smb-storage-pv
  resources:
    requests:
      storage: 10Gi
