apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: '>=6.0.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 1h
  install:
    timeout: 15m
    crds: Create
  upgrade:
    timeout: 15m
    crds: CreateReplace
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
          - from: 2025-12-01
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: nfs
        size: 10Gi
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
