apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
  namespace: sftp-csi-driver
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-rclone
      version: '>=1.3.0'
      sourceRef:
        kind: HelmRepository
        name: csi-rclone
        namespace: sftp-csi-driver
      interval: 12h
  values:
    storageClass:
      enabled: false
