apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager
spec:
  interval: 1h
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: '0.8.1-alpha.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
        namespace: cert-manager
      interval: 1h
  install:
    timeout: 15m
  upgrade:
    timeout: 15m
  values:
    groupName: acme.stoinski.pro
    configVersion: 0.0.2
