apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager
spec:
  interval: 1h
  url: https://aureq.github.io/cert-manager-webhook-ovh
